name: Run Multipass_ca.sh

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run Multipass_ca.sh
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Multipass
      uses: appleboy/multipass-action@master

    - name: Execute Multipass_ca.sh
      run: bash Multipass_ca.sh
